### ISSUE TITLE
Wrong eyeplacement in 1440p

### ISSUE THREAD

**Issue by benomat** [Pimeko/RhythmParadiseLively#1]
The eyes are in  the wrong position when I use 1440p.
![image](https://user-images.githubusercontent.com/71938735/138365468-d38b5e01-1566-4eaf-b139-59042cf8a5ff.png)

**Comment by Pimeko** [comment]
Right, it was only made for 1920x1080 screens, but I'll make it responsive when I have the time!

**Comment by Pimeko** [comment]
This is now fixed thanks to @DaXmAn !

**Comment by Pimeko** [comment]
This is now fixed thanks to @DaXmAn !
